**Excercise 1**

In [2]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_sums = np.einsum('ij -> j', A)
print (column_sums) # Output : [12 15 18]

[12 15 18]


**Excercise 2**

In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.einsum('ij,ij ->', A, B)
print(dot_product)


70


In [8]:
import numpy as np

A = np . array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_sum = np.einsum('ii->', A)
print (diagonal_sum) # Output : 15

15


In [12]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.einsum('ij,jk -> ik ', A, B)
print(dot_product)


[[19 22]
 [43 50]]


In [14]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
outer_product =np.einsum('i,j -> ij', a, b)
print (outer_product) 

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [8]:
import numpy as np

def gram_matrix(tensor: np.ndarray):
    # tensor có kích thước (channels, height, width)
    channels, height, width = tensor.shape
    # Chuyển tensor thành ma trận 2D có kích thước (channels, height * width)
    features = tensor.reshape(channels, height * width)
    print("Features sau khi reshape:\n", features)
    # Tính Gram matrix sử dụng dot product với einsum
    gram = np.einsum('ik,jk->ij', features, features)
    return gram


# Tạo tensor ngẫu nhiên với kích thước (channels, height, width)
tensor = np.random.rand(3, 4, 4)
gram = gram_matrix(tensor)
print("Ma trận Gram cuối cùng:\n", gram)

Features sau khi reshape:
 [[0.4440415  0.69470015 0.58443806 0.21208644 0.1351421  0.79990531
  0.51908618 0.16737974 0.2383342  0.39092763 0.62605942 0.9680278
  0.31674121 0.62904514 0.67112397 0.63115028]
 [0.64077305 0.58023377 0.16220528 0.37972399 0.51952367 0.10900104
  0.20993916 0.33292696 0.04114273 0.63127116 0.09929257 0.93060506
  0.60562416 0.05782348 0.80330183 0.86452291]
 [0.35129653 0.86568978 0.94265554 0.25202463 0.93007555 0.42188425
  0.1025197  0.85836053 0.70243886 0.08306646 0.89904447 0.6030863
  0.62363813 0.98161573 0.43865421 0.33248415]]
Ma trận Gram cuối cùng:
 [[4.90534466 3.71761372 4.68760744]
 [3.71761372 4.39336174 3.6185876 ]
 [4.68760744 3.6185876  6.94303547]]



Gram Matrix $G$ có kích thước $(C, C)$ và được tính bằng công thức:
- Cách 1 : không cần nhân chuyển vị khi tích vô hướng
$\begin{equation}
G_{ij} = \sum_{k} F_{ik} F_{jk}
\end{equation}$

- Cách 2 : Nhân với ma trận chuyển vị 
$\begin{equation}
G_{ik} = \sum_{j} F_{ij} {F^{T}}_{jk}
\end{equation}$


In [7]:
import numpy as np

V = np.array([[1, 2, 3], [4, 5, 6]])
V_transpose = V.T


gram_correct = np.einsum('ik,jk -> ij', V, V)

# từng hàng của của ma trận A nhân lần lượt với hàng của A_T
gram_correct2 = np.einsum('ij,jk -> ik', V, V_transpose)
print("Ma trận V:")
print(V)
print("\nMa trận chuyển vị của V, V^T:")
print(V_transpose)
print("\nMa trận Gram đúng, sử dụng 'ik,jk -> ij':")
print(gram_correct)
print("\nMa trận Gram đúng, sử dụng 'ij,jk -> ik':")
print(gram_correct2)

Ma trận V:
[[1 2 3]
 [4 5 6]]

Ma trận chuyển vị của V, V^T:
[[1 4]
 [2 5]
 [3 6]]

Ma trận Gram đúng, sử dụng 'ik,jk -> ij':
[[14 32]
 [32 77]]

Ma trận Gram đúng, sử dụng 'ij,jk -> ik':
[[14 32]
 [32 77]]
